### PR TITLE
adding tf tensors

### PR DESCRIPTION
**Pull request by chappers**
Patch for Tensorflow Tensors, before it was on tf.variables which were enabled.

tf_tensor

### CODE REVIEW

**Comment by lckr** [comment]
How do we deal with tensors of order higher than two? I'm not sure if the datagrid widget can cope with that. Would you mind to check?

**Comment by chappers** [comment]
Not sure what the solution is there either. 

We'll need to figure out how to deal with it from numpy perspective as the tensor variables get converted to numpy first. As a simple experiment currently:

```py
import numpy as np
a = np.random.normal(size=(1,2,3))
```

Will appear in the variable explorer but will not open in the datagrid widget:

image

**Comment by chappers** [comment]
@lckr how would you like to proceed with this? 

Something like a warning or message should pop up if we do try to view n-d arrays in numpy as well?

**Comment by lckr** [comment]
My idea is to either mark higher order tensors as "not-a-matrix" and don't make them inspectable, i.e. styling them the same way as non clickable variables such as integers. And optional we can show some message in the `context` field in the new title.

**Comment by chappers** [comment]
@lckr just updated so it is not a matrix when shape of tensor and ndarray is greater than 2

**Comment by lckr** [comment]
Do you know how they cope with that in spyder?

**Comment by lckr** [comment]
Thanks for your research. For now, I think it is a good enough to just disable the inspection of matrices w/ more than two dimensions. Implementing some kind of support for higher order tensors is a feature for future versions but not necessarily needed in the beta-release. Do you agree?

**Comment by chappers** [comment]
Yes I agree let's put it down for future

**Pull request merged**
