### PR TITLE
Quotes and series display

### LINKED ISSUE #85: if size of dataframe and numpy are too big, it cant be visualized
if size of dataframe and numpy are too big, it cant be visualized.

Screen Shot 2019-04-16 at 1 45 38 AM

i can view news2,
 but not news

### PR DESCRIPTION
**Pull request by sho-87**
Fixes #85 and #86

Dataframes containing `'` or `"` characters should now open correctly

An example of problematic content in a data cell would be `Romancing the Tale: Walt Disney's Adaptation of the Grimms' "Snow White"`

Previously the quote characters were not escaped correctly, and therefore could not be parsed by the json module

### CODE REVIEW

**Comment by sho-87** [comment]
Added a few more changes:
- Pandas series were not opening correctly. They were handled the same way as dataframes, but series dont have column names, which was causing an error
- Added series contents to the contents column rather than just a row count
- Removed line breaks for series content
- Removed a few brackets `[]` that were not serving any purpose and just taking up screen real estate
- Added a dict description to the shape column
- Allow lists to be inspectable (I'm treating them the same as a pandas series)
- Changed the inspection tab name from `Matrix: ...` to `[varType]: ....` as now more than matrices can be inspected

**Comment by sho-87** [comment]
@lckr no problem. theyve mostly been small tweaks here and there but I have a bigger commit coming in soon (hopefully). ill let you know when its done and then you can merge everything in

also, is it ok if I run the prettier formatter over everything just to tidy up the code a bit?

**Comment by sho-87** [comment]
@lckr actually ill leave the formatting alone for now. maybe ill do that in another pull request as things would get quite messy

I just added the ability to delete variables. should work for both python and R

everything is ready to be reviewed and merged in when you get a chance

**Comment by sho-87** [comment]
@lckr I think you'll have to merge this in as I dont have write access

**Comment by lckr** [comment]
you should be able to merge now.

**Comment by sho-87** [comment]
@lckr does a new package need to be pushed to npm for `jupyter labextension install @lckr/jupyterlab_variableinspector` to get the latest? or would a simple version bump in this repo be enough?

**Comment by lckr** [comment]
I will publish the new version right now.

**Comment by lckr** [comment]
Done.

**Pull request merged**
