### PR TITLE
Update for JupyterLab 1.0 support

### PR DESCRIPTION
**Pull request by ihenry42**
I have been able to get the extension running in JupyterLab 1.0 with these changes.

### CODE REVIEW

**Comment by carlosnatalino** [comment]
Has this change been merged into master? When I clone from master, still don't get this version.

**Comment by ihenry42** [comment]
> 
> 
> Has this change been merged into master? When I clone from master, still don't get this version.

I don't think so, just pull from my fork until it is merged, or 1.0 is otherwise supported.

**Comment by carlosnatalino** [comment]
> > Has this change been merged into master? When I clone from master, still don't get this version.
> 
> I don't think so, just pull from my fork until it is merged, or 1.0 is otherwise supported.

Thanks! FYI it worked just fine for me as well.

**Comment by lckr** [comment]
New version was published to npm and can be installed from there.

**Pull request merged**
