### PR TITLE
R langsupport

### PR DESCRIPTION
**Pull request by lckr**
This PR is to track the progress of the R support.

@chappers What's your opinion about the state of the current R-script?

### CODE REVIEW

**Comment by chappers** [comment]
I haven't done much more on it. I have a paper due + will be going on a 3 week holiday, coming back in September, so won't have much time unfortunately...

**Comment by lckr** [comment]
Don't worry, I will also be on vacation in the next weeks returning in the first week of September.

**Comment by sho-87** [comment]
@chappers @lckr would it be a good idea to separate language scripts into different files, just to make things easier moving forward if more extensive language support is expected?

**Comment by chappers** [comment]
Finally had a bit of time to revisit this

r_lang_support

Demo to show that it "works" - you can see from the changes, we probably don't want to merge as is. There is a difference in how `jsonlite` in R dumps `json` objects and Python's `json` library. 

Not sure where we want this to be handled. Right now its really a patchup just to get the MVP over the line.

**Comment by chappers** [comment]
Closes #5

**Pull request merged**
